[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "automation"
startCommand = "node ai-agent/SUPER_AUTOMATION.js"

[services.cron]
schedule = "0 9 * * *"  # Daily at 9 AM

[[services]]
name = "telegram-bot"
startCommand = "node ai-agent/telegram-bot.js"

[[services]]
name = "api"
startCommand = "node server.js"

[services.healthcheck]
path = "/health"
timeout = 100

[env]
NODE_ENV = "production"
